import { test, expect } from './fixtures.js'
import { MIN_X, MAX_X, MIN_Z, MAX_Z, SURFACE_Y, ID, look, waitTicks, HEADING } from './helpers/world.js'
import { CHAPTERS, LAND_ORIGIN_X, LAND_ORIGIN_Z } from '../src/builds/plots.js'

/*
 * Which way round the world is.
 *
 * ------------------------------------------------------------------------
 * WHAT THIS FILE USED TO ASSERT, AND WHY IT IS NOT THAT ANY MORE.
 *
 * The overworld shipped for a while as a 128x128 cut of Minecraft seed 12345,
 * and for a while before THAT it shipped as a MIRROR IMAGE of the same cut.
 * Nothing looked broken, because everything downstream inherited the mirror
 * and agreed with it -- a mirrored world is self-consistent, and is only
 * wrong against the outside. So two of the tests here named columns of that
 * save: frozen peaks sixteen blocks higher on one side of spawn than the
 * other, dark oak leaves at y=140 over the spawn column.
 *
 * THE SAVE IS GONE. The overworld is generated by src/flatworld.js and
 * src/builds/land.js, there is no public/terrain.bin on its boot path, and
 * both of those tests were measuring a world that no longer exists. They
 * failed with numbers from a landscape nobody can walk to, which is the
 * loudest kind of fossil and still a fossil.
 * ------------------------------------------------------------------------
 * WHAT REPLACED THEM HAS TO DO THE SAME JOB, which is the part worth getting
 * right. A handedness bug is invisible to any single self-consistent world,
 * so each test below is one of the two kinds of claim a mirror cannot
 * satisfy at once:
 *
 *   1. A measurement of the ENGINE, not of the content: at heading 0 the
 *      camera faces +Z, and a point at +X lands on the right of the screen.
 *      Every cardinal name in this repo -- the F3 compass, the stair facings
 *      in blockMeshes.js -- is chosen from that one fact, and it is measured
 *      here so nobody has to trust a comment about handedness.
 *
 *   2. Claims that tie the ENGINE to the SURVEY, which is where the outside
 *      referent lives now that the terrain is ours. src/builds/plots.js calls
 *      chapter 1 LEFT and chapter 2 RIGHT, and those words are a promise about
 *      which hand a visitor walking south finds them on. A mirror keeps every
 *      coordinate in that table and swaps the hands, so projecting the two
 *      plots through the real camera is exactly the check the table cannot
 *      make about itself. The massif is the same claim in x alone: it stands
 *      EAST of the climb's plot, and the compass has to agree that the
 *      direction it stands in is east.
 *
 * See the compass note in src/debugScreen.js for why +X is west and cannot be
 * anything else.
 */

/** Patch indices -> world coordinates, the overworld's origin. */
const W = (px, pz) => [px - LAND_ORIGIN_X, pz - LAND_ORIGIN_Z]

/** The topmost non-air block of a column, asked of the GENERATOR so it works
 *  on chunks that are nowhere near the player. */
const surfaceY = (page, x, z) => page.evaluate(([x, z]) => {
  for (let y = 185; y >= -64; y--) if (window.game.voxelAt(x, y, z) !== 0) return y
  return null
}, [x, z])

const press = async (page, code) => {
  await page.keyboard.down(code)
  await page.keyboard.up(code)
  await waitTicks(page, 2)
}

test.describe('world orientation', () => {
  /*
   * The measurement. Projected through the scene's full transform -- view
   * AND projection -- rather than read off the view matrix, because the
   * handedness can hide in either and only the composition is what a player
   * sees.
   */
  test('facing +Z, the +X axis is on the right of the screen', async ({ page }) => {
    await look(page, { heading: 0, pitch: 0 })
    const { rightHanded, camDir, ndcPlusX, ndcMinusX } = await page.evaluate(() => {
      const noa = window.noa
      const scene = noa.rendering.getScene()
      const eye = scene.activeCamera.globalPosition
      const m = scene.getTransformMatrix().m
      // Babylon stores row-major with a row-vector convention: v' = v * M.
      const ndcX = (px, py, pz) => {
        const x = px * m[0] + py * m[4] + pz * m[8] + m[12]
        const w = px * m[3] + py * m[7] + pz * m[11] + m[15]
        return x / w
      }
      return {
        rightHanded: scene.useRightHandedSystem,
        camDir: [...noa.camera.getDirection()],
        // Twenty blocks ahead, ten to each side.
        ndcPlusX: ndcX(eye.x + 10, eye.y, eye.z + 20),
        ndcMinusX: ndcX(eye.x - 10, eye.y, eye.z + 20),
      }
    })

    // The premise: noa's heading 0 looks down +Z, in a left-handed scene.
    expect(rightHanded).toBe(false)
    expect(camDir[2]).toBeCloseTo(1, 3)

    // The consequence. Minecraft, facing south, puts WEST on your right --
    // which is why +X is west here and `east = [-1, 0, 0]` in blockMeshes.js.
    expect(ndcPlusX).toBeGreaterThan(0)
    expect(ndcMinusX).toBeLessThan(0)
  })

  /*
   * The patch is 128 wide with the spawn column at the origin, and the spawn
   * column is 87 in from the asset's east edge -- so x runs -87..40, and the
   * asymmetry runs the OPPOSITE way to the one that shipped before (-40..87).
   * Asserted because a stale mental model gets exactly this wrong, and because
   * the numbers here and in island.js have to stay in step.
   */
  test('the patch runs -128..127 in x and -16..239 in z', async ({ page }) => {
    /* Was -87..40 / -56..71, when the overworld was a 128 patch at origin
     * 87/56. It is 256 at origin 128/16 now: centred on x so the path may
     * wander either side of you, and offset on z so spawn is at the START of
     * the walk rather than in the middle of it. */
    expect([MIN_X, MAX_X, MIN_Z, MAX_Z]).toEqual([-128, 127, -16, 239])
    expect(await page.evaluate(() => window.game.terrain.originX)).toBe(128)
    expect(await page.evaluate(() => window.game.terrain.originZ)).toBe(16)

    expect(await page.evaluate(([x, y, z]) => window.game.voxelAt(x, y, z),
      [MIN_X, SURFACE_Y - 1, 0])).not.toBe(ID.barrier)
    expect(await page.evaluate(([x, y, z]) => window.game.voxelAt(x, y, z),
      [MAX_X + 1, SURFACE_Y - 1, 0])).toBe(ID.barrier)
  })

  /*
   * THE ONE THAT DISCRIMINATES, AND IT IS THE PLOT TABLE'S OWN WORDS.
   *
   * src/builds/plots.js labels chapter 1 LEFT and chapter 2 RIGHT, and the
   * long note above CHAPTERS explains that LEFT is the LOW-x side because
   * Babylon is left-handed and the visitor walks south. That paragraph is a
   * claim about what a person SEES, made by a file that contains nothing but
   * indices, and it is exactly the claim a mirrored world satisfies with the
   * hands swapped and no number changed.
   *
   * So it is measured the only way it can be: stand at spawn facing down the
   * walk and project the middle of each plot through the scene's real
   * transform. LEFT has to land on the left of the screen. If the handedness
   * ever flips, every `side` in the table silently becomes a lie and this is
   * the line that says so.
   */
  test('the plot table\'s LEFT and RIGHT are the visitor\'s, walking south',
    async ({ page }) => {
      await look(page, { heading: HEADING.southPlusZ, pitch: 0 })
      const mid = (c) => W(Math.round((c.x0 + c.x1) / 2), Math.round((c.z0 + c.z1) / 2))
      const ch1 = CHAPTERS.find(c => c.id === 'ch1')
      const ch2 = CHAPTERS.find(c => c.id === 'ch2')
      expect(ch1.side, 'the table stopped saying what this test reads').toBe('LEFT')
      expect(ch2.side).toBe('RIGHT')

      const ndc = await page.evaluate(([a, b, y]) => {
        const noa = window.noa
        const scene = noa.rendering.getScene()
        const m = scene.getTransformMatrix().m
        /*
         * THROUGH globalToLocal FIRST, and this is the trap in the whole
         * measurement. noa renders on a FLOATING ORIGIN: the Babylon scene
         * keeps the camera near (0, 0, 0) and shifts the world under it, so a
         * world coordinate handed straight to the scene's transform is a
         * point a hundred blocks from where the spec meant. It projects to a
         * number either way, which is how a test like this passes while
         * measuring nothing -- the first version of this one survived being
         * pointed the wrong way down the map.
         */
        const at = ([px, pz]) => {
          const [lx, ly, lz] = noa.globalToLocal([px, y, pz], null, [])
          // Babylon stores row-major with a row-vector convention: v' = v * M.
          const x = lx * m[0] + ly * m[4] + lz * m[8] + m[12]
          const w = lx * m[3] + ly * m[7] + lz * m[11] + m[15]
          return { ndc: x / w, w }
        }
        return { left: at(a), right: at(b) }
      }, [mid(ch1), mid(ch2), SURFACE_Y])

      /*
       * THE SAMPLE, BEFORE THE CLAIM, and for this measurement the sample is
       * `w`. A point BEHIND the camera has w < 0 and its projected x comes
       * back with the sign flipped, so "left of the screen" would be read off
       * a plot that is not on the screen at all. Both chapters are south of
       * spawn and the visitor is facing south, so both have to be in front.
       */
      expect(ndc.left.w, 'ch1 is behind the camera').toBeGreaterThan(0)
      expect(ndc.right.w, 'ch2 is behind the camera').toBeGreaterThan(0)
      expect(ndc.left.ndc, `ch1 is labelled LEFT and projected to ${ndc.left.ndc}`)
        .toBeLessThan(0)
      expect(ndc.right.ndc, `ch2 is labelled RIGHT and projected to ${ndc.right.ndc}`)
        .toBeGreaterThan(0)
    })

  /*
   * THE SAME CLAIM IN x ALONE, and it is the one the mountain makes.
   *
   * src/builds/biomes.js stands the massif beside chapter 6 rather than under
   * it -- the climb has to stay flat -- and "beside" is a direction: the
   * summit is at a LOWER patch x than the climb's plot, and lower x is EAST
   * in this engine. Both halves are asserted, because either one alone is
   * satisfied by a mirror that also moved the compass.
   *
   * The peak is FOUND rather than typed. SUMMIT is a private constant in
   * biomes.js and a spec that copied its coordinates would be asserting its
   * own copy; scanning the southern quarter for the highest column asks the
   * world where the mountain actually came out.
   */
  test('the massif stands east of the climb, and the compass agrees',
    async ({ page }) => {
      const climb = CHAPTERS.find(c => c.id === 'ch6')
      const peak = await page.evaluate(([ox, oz, floor]) => {
        const v = window.game.voxelAt
        let best = { h: -999, px: -1, pz: -1 }
        let sampled = 0
        // The southern quarter, every other column. The peaks biome and both
        // of its anchors live below patch z = 200.
        for (let pz = 200; pz < 256; pz += 2) {
          for (let px = 0; px < 256; px += 2) {
            sampled++
            for (let y = 199; y >= floor; y--) {
              if (v(px - ox, y, pz - oz) === 0) continue
              if (y > best.h) best = { h: y, px, pz }
              break
            }
          }
        }
        return { ...best, sampled }
      }, [LAND_ORIGIN_X, LAND_ORIGIN_Z, SURFACE_Y - 4])

      // The sample, before the claim. A scan that found nothing has a very
      // clear opinion about where the mountain is.
      expect(peak.sampled).toBeGreaterThan(3_000)
      expect(peak.px, 'nothing solid in the southern quarter').toBeGreaterThan(-1)
      /* A mountain, not a bump: the climb's own plot is pinned flat at
       * SURFACE_Y - 1 and the massif has to be visibly above it. */
      expect(peak.h - (SURFACE_Y - 1),
        `the highest column in the south is only ${peak.h - SURFACE_Y + 1} above the ground`)
        .toBeGreaterThan(8)
      expect(peak.px,
        `the peak is at patch x ${peak.px}, the climb runs ${climb.x0}..${climb.x1}`)
        .toBeLessThan(climb.x0)

      await press(page, 'F3')
      await look(page, { heading: HEADING.eastMinusX, pitch: 0 })
      const s = await page.evaluate(() => window.game.debug.sample())
      expect(s.facing).toBe('east')
      await press(page, 'F3')
    })

  /*
   * SPAWN, AND THE CLEARING OVER IT.
   *
   * This used to read "spawn is the same Minecraft column it always was" and
   * check for dark oak leaves at y = 140. There is no Minecraft column and no
   * dark oak; what is true of this world is the thing two other spec files
   * depend on without knowing it -- SPAWN_CLEAR in src/builds/land.js keeps
   * eight blocks around the origin with nothing standing in them, so the rigs
   * 17-non-cube and 66-torch build at spawn are built in open air.
   *
   * The block under your feet is the PATH, not grass: the walk runs through
   * spawn and its surface replaces the grass at the same height. That is the
   * half that tells this world from a bare superflat.
   */
  test('spawn is the origin, on the path, with nothing standing over it',
    async ({ page }) => {
      const under = await page.evaluate(([y]) => window.game.voxelAt(0, y, 0),
        [SURFACE_Y - 1])
      expect(under).not.toBe(ID.air)
      expect(under).not.toBe(ID.grass)
      // Nothing above it, all the way up: the topmost solid block IS the one
      // under your feet.
      expect(await surfaceY(page, 0, 0)).toBe(SURFACE_Y - 1)
    })
})
