import { BLOCK_TYPES, BLOCK_BY_ID } from './blocks.js'
import { ITEMS, stackMax } from './items.js'

/*
 * The creative item picker: which tab every item lives in.
 *
 * This file is the CATEGORISATION. The screen that draws it lives at the
 * bottom; the interesting half is above it, and the interesting half is a
 * table of ordered rules rather than 508 hand-written lines.
 *
 * WHY RULES. This codebase has twice shipped a lookup with a handful of
 * entries and a catch-all default, and both times the default was a bug you
 * could see: sounds.js defaulted to `stone`, so leaves and snow crunched like
 * rock, and `dropFor` defaulted to self, so every ore dropped itself. Both are
 * now ordered rules over the block KEY with no catch-all and a report of what
 * matched nothing, asserted empty by a test. That is the pattern here, for the
 * same reason -- a "Miscellaneous" tab is a default with a friendly name, and
 * the day somebody adds a block, they would never find out it landed there.
 *
 * So: `uncategorisedItems()` lists every registered item no rule claims, and
 * test/31-creative.spec.js fails on a non-empty list.
 *
 * WHAT THE RULES MATCH. The item key, which for a block item is the block key.
 * Keys are generated by blocks.js in whole families (`dyed()`, `woodSet()`,
 * `nonCubeSet()`), so the naming convention IS the categorisation: every dyed
 * wool ends in `_wool`, every stair in `_stairs`, every stripped log starts
 * `stripped_`. Rejected: a `tab:` field on each block definition. It is the
 * most direct expression of this and it is 508 edits in another agent's file,
 * and it would not have caught the case these rules exist to catch -- a new
 * block arriving with no field set looks exactly like a block that matched no
 * rule, except nothing is watching.
 */

/* ------------------------------------------------------------------ *
 * The tabs.
 *
 * Vanilla's set, not a set invented here. 1.19.3 replaced the nine-tab
 * arrangement everyone remembers (Building Blocks / Decoration Blocks /
 * Redstone / Transportation / Miscellaneous / Food / Tools / Combat /
 * Brewing). minecraft.wiki/w/Creative: "In Java Edition, there are 13 (14 if
 * Operator Utilities tab is enabled in settings) tabs that are ordered from
 * top-left to bottom-right as" --
 *
 *   TOP     Building Blocks, Colored Blocks, Natural Blocks,
 *           Functional Blocks, Redstone Blocks, Saved Hotbars, Search Items
 *   BOTTOM  Tools & Utilities, Combat, Food & Drinks, Ingredients,
 *           Spawn Eggs, [Operator Utilities], Survival Inventory
 *
 * Seven per row is the FORMAT's limit, not a coincidence:
 * minecraft.wiki/w/Java_Edition_GUI_textures lists exactly
 * tab_top_selected_1..7, tab_top_unselected_1..7 and the two bottom sets, so
 * CreativeModeTab.Row is TOP/BOTTOM with a column of 0-6 and nothing else
 * fits. NOTE the row split is inferred from those sprite names plus
 * "top-left to bottom-right"; the wiki never states it as a sentence.
 *
 * Four of vanilla's fourteen are deliberately absent, and each absence is a
 * fact about THIS world rather than a shortcut:
 *
 *   Spawn Eggs          there are no mobs. The tab would be empty.
 *   Food & Drinks       nothing is edible here. survival.js drains a hunger
 *                       bar; no item restores it, so the tab would be empty.
 *   Operator Utilities  its entire content here would be the barrier block,
 *                       which items.js deliberately has no item for (it is
 *                       `invisible`, so there is no icon to draw and nothing
 *                       should ever hold one). Vanilla hides this tab unless
 *                       the "Operator Items Tab" option is on, so an absent
 *                       op tab is the vanilla DEFAULT, not a gap.
 *   Saved Hotbars       C+1-9 saves a hotbar and X+1-9 loads it, stored
 *                       globally rather than per world. That is a keybinding
 *                       feature and a persistence feature wearing a tab; the
 *                       tab without them would be five rows of the
 *                       instructional paper item and nothing else.
 *
 * `column` is NOT vanilla's raw column, it is the position after the absent
 * tabs are closed up -- which is vanilla's own behaviour: with Operator
 * Utilities off, Survival Inventory slides from column 6 to column 5 rather
 * than leaving a hole. Holes read as a broken screen.
 *
 * ICONS. Vanilla's are Bricks / Cyan Wool / Grass Block / Oak Sign /
 * Redstone Dust / Diamond Pickaxe / Netherite Sword / Iron Ingot / Compass /
 * Chest. Four of those do not exist in this world -- there is no grass block
 * in the palette, no sign, no compass, and items.js explains at length why
 * there is no chest item (it has no flat sprite anywhere in Minecraft, only
 * an entity model). The substitutes are the nearest thing that IS here, and
 * each is named below so the swap is visible rather than mysterious.
 *
 * An empty tab is worse than a missing one, so the loop at the end of this
 * file throws at module load if a declared tab has no items.
 * ------------------------------------------------------------------ */
export const TABS = [
  { id: 'building_blocks', label: 'Building Blocks', row: 'top', column: 0, icon: 'bricks' },
  { id: 'colored_blocks', label: 'Colored Blocks', row: 'top', column: 1, icon: 'cyan_wool' },
  { id: 'natural_blocks', label: 'Natural Blocks', row: 'top', column: 2, icon: 'grass' },
  // Vanilla: Oak Sign. No signs here; the crafting table is the most
  // recognisable thing in the tab.
  { id: 'functional_blocks', label: 'Functional Blocks', row: 'top', column: 3, icon: 'crafting_table' },
  { id: 'redstone_blocks', label: 'Redstone Blocks', row: 'top', column: 4, icon: 'redstone' },
  /*
   * The two special tabs, which hold no category of their own. `special` is
   * what keeps them out of the rule table: "which items are in the Search
   * tab" is a question about a text field, not about categories.
   *
   * Search sits at the END of the top row, which is vanilla's placement --
   * it is tab 7 of the top row, immediately after Saved Hotbars.
   */
  // Vanilla: Compass. Not in this item table; a bookshelf is vanilla's own
  // icon for the neighbouring Saved Hotbars tab, so it is at least in the
  // right visual neighbourhood.
  { id: 'search', label: 'Search Items', row: 'top', column: 5, icon: 'bookshelf', special: 'search' },

  { id: 'tools_and_utilities', label: 'Tools & Utilities', row: 'bottom', column: 0, icon: 'diamond_pickaxe' },
  { id: 'combat', label: 'Combat', row: 'bottom', column: 1, icon: 'netherite_sword' },
  { id: 'ingredients', label: 'Ingredients', row: 'bottom', column: 2, icon: 'iron_ingot' },
  // Vanilla: Chest, at the far right of the bottom row. A barrel is the only
  // other container in the palette and it is the one that has a sprite.
  { id: 'inventory', label: 'Survival Inventory', row: 'bottom', column: 3, icon: 'barrel', special: 'inventory' },
]

/** The tabs that list items by rule -- everything but Search and Inventory. */
export const CATEGORY_TABS = TABS.filter(t => !t.special)

/* ------------------------------------------------------------------ *
 * Rules.
 *
 * Ordered. First match wins, so the file reads top to bottom as "the most
 * specific claim, then the next". Each row is `[pattern, tab, why]` and `why`
 * is the vanilla fact it encodes -- these were read off the wiki's per-tab
 * item lists, not guessed, and the string is there so the next person can
 * check one rule without rereading all of them.
 *
 * The one structural trick: the 28 non-cube families are stripped of their
 * `_slab` / `_stairs` suffix and asked again, exactly as sounds.js does. A
 * cherry stair is whatever cherry planks are, forever, with no rule of its
 * own -- which is also why adding a family to blocks.js needs no edit here.
 * ------------------------------------------------------------------ */
const RULES = [
  /* ---- not blocks at all, first: several of these carry material names
     that the block rules below would happily claim (a `stone_pickaxe` is not
     stone, a `nether_brick` item is not nether bricks). ---- */
  [/_(sword|bow)$|^(bow|arrow)$|_(helmet|chestplate|leggings|boots)$/, 'combat',
    'vanilla moved all armor into Combat in 1.19.3; swords, bows and arrows were already there'],
  [/_(pickaxe|axe|shovel|hoe)$|^(shears|flint_and_steel|bucket|water_bucket|lava_bucket|fishing_rod)$/,
    'tools_and_utilities',
    'Tools & Utilities: the five tool shapes plus shears, flint and steel, buckets and rods. '
    + 'The filled buckets are spelled out rather than matched as a `_bucket` suffix, because '
    + 'vanilla files the MILK bucket under Foods -- a suffix rule would be wrong the day it lands'],
  [/^(stick|coal|charcoal|flint|clay_ball|leather|string|feather|gunpowder|paper|book|wheat|slime_bal)/,
    'ingredients', 'Ingredients holds every crafting material that is not a block'],
  [/^(iron|gold|copper|netherite)_(ingot|nugget|scrap)$|^raw_(iron|gold|copper)$/, 'ingredients',
    'ingots, nuggets and raw metal are Ingredients; their BLOCKS are Natural'],
  [/^(diamond|emerald|lapis_lazuli|redstone|quartz|amethyst_shard)$/, 'ingredients',
    'the bare gems and dusts are Ingredients; the blocks of them are Natural'],
  [/^(brick|nether_brick)$/, 'ingredients',
    'the brick ITEM, not `bricks` the block -- the singular key is the item'],
  [/^bowl$/, 'ingredients', 'vanilla files the empty bowl under Ingredients'],
  [/^(sugar_cane|bamboo)$/, 'ingredients',
    'vanilla has these as Natural Blocks because they ARE blocks there; here they '
    + 'are items with no block, and an item in a block tab would be a lie about what it places'],
  /*
   * Signs, which vanilla files under Functional Blocks beside the torch and
   * the ladder. Only the canonical `oak_sign` reaches this table at all --
   * the other seven ids carry `drops`, so items.js never makes them items --
   * but the pattern is written to match the family rather than the one key,
   * for the same reason the stair rule is: the second wood's signs should
   * land here the day they exist, not fall off the end into the report.
   */
  [/^\w+_sign$/, 'functional_blocks',
    'Functional Blocks, where vanilla lists signs -- next to the torch, and for '
    + 'the same reason: it is a block you place to do a job rather than to build with'],
  [/^(torch|ladder)$/, 'functional_blocks',
    'Functional Blocks, which is where vanilla lists both. The torch is a real '
    + 'block now and places one; the ladder is still unplaceable (no block mesh, '
    + 'see items.js), and the tab is about what the thing IS either way'],

  /* ---- colour, before the material rules: a `blue_concrete` is colour
     first and concrete second, which is exactly what the tab means ---- */
  [/_(wool|carpet)$/, 'colored_blocks', 'Colored Blocks: the sixteen wools'],
  [/_concrete(_powder)?$/, 'colored_blocks', 'Colored Blocks: concrete and concrete powder'],
  [/^(\w+)_(glazed_)?terracotta$/, 'colored_blocks',
    'Colored Blocks: the dyed and glazed terracottas. Plain `terracotta` has no '
    + 'colour prefix so it falls past this to Natural, which is where vanilla files it'],
  [/_stained_glass$/, 'colored_blocks', 'Colored Blocks: stained glass'],

  /* ---- redstone, before the stone and utility rules eat the components ---- */
  [/^(redstone_block|redstone_lamp|target|observer|piston|sticky_piston|dispenser|dropper|tnt)$/,
    'redstone_blocks',
    'Redstone Blocks. Note the Block of Redstone is here rather than with the '
    + 'other mineral blocks -- vanilla treats it as a component, because it is one'],

  /* ---- functional: the blocks you right-click or that emit light ---- */
  [/^(crafting_table|furnace|blast_furnace|smoker|bookshelf|chiseled_bookshelf|barrel|loom|cartography_table|fletching_table|smithing_table|beehive|bee_nest|note_block|jukebox|lodestone|respawn_anchor)$/,
    'functional_blocks', 'Functional Blocks: the workstations and the interactables'],
  [/^(glass|tinted_glass)$/, 'functional_blocks',
    'glass moved out of Building Blocks into Functional Blocks in the 1.19.3 reshuffle'],
  [/^(sea_lantern|glowstone|shroomlight|ochre_froglight|verdant_froglight|pearlescent_froglight)$/,
    'functional_blocks', 'Functional Blocks collects the light sources'],
  [/^(hay_block|dried_kelp_block|honeycomb_block|slime_block|sponge|wet_sponge)$/,
    'functional_blocks', 'Functional Blocks: the odd-behaviour blocks (bouncy, absorbent, compostable)'],

  /* ---- natural: what the world generator puts down ---- */
  [/_ore$|^ancient_debris$/, 'natural_blocks', 'ores generate; Natural Blocks'],
  [/^(coal|iron|gold|diamond|emerald|lapis|netherite)_block$|^raw_(iron|copper|gold)_block$/,
    'natural_blocks', 'the mineral storage blocks sit with their ores in Natural Blocks'],
  [/_(log|wood|stem|hyphae|leaves)$|^(stripped_)?bamboo_block$/, 'natural_blocks',
    'logs, the bark-on-six-sides `_wood` forms, their stripped variants and leaves'],
  [/^(grass|podzol|mycelium|dirt|coarse_dirt|rooted_dirt|mud|clay|gravel|sand|red_sand|snow_block|ice|packed_ice|blue_ice|moss_block|terracotta)$/,
    'natural_blocks', 'the surface materials, plus plain undyed terracotta (a badlands block)'],
  // The two nylia are Natural for the same reason grass is: they are a
  // surface that spreads, not a thing anybody crafts.
  [/nylium$/, 'natural_blocks', 'crimson and warped nylium generate in the nether forests'],
  [/^(stone|andesite|diorite|granite|tuff|calcite|dripstone_block|deepslate|cobbled_deepslate|smooth_basalt|basalt|blackstone|obsidian|crying_obsidian|magma_block|bedrock|reinforced_deepslate)$/,
    'natural_blocks', 'the rock the world is made of, in its as-generated form'],
  [/^(netherrack|soul_sand|soul_soil|nether_wart_block|warped_wart_block|sculk|sculk_catalyst|end_stone|prismarine|dark_prismarine|amethyst_block|budding_amethyst|bone_block|resin_block)$/,
    'natural_blocks', 'the nether, the end, the deep dark and the ocean monument, as generated'],
  [/^(melon|pumpkin|carved_pumpkin|jack_o_lantern|brown_mushroom_block|red_mushroom_block|mushroom_stem)$/,
    'natural_blocks', 'crops and huge-mushroom blocks generate or grow; Natural Blocks'],
  [/^copper_(ore|block)$|^(exposed|weathered|oxidized)_copper$/, 'natural_blocks',
    'the un-cut copper blocks oxidise on their own, so vanilla files them as natural. '
    + 'CUT copper is a player-made shape and falls through to Building Blocks'],

  /* ---- building blocks last, and ENUMERATED.
     A trailing [/./, 'building_blocks'] would make this table impossible to be
     wrong about, and impossible to notice being wrong -- which is the exact
     failure the whole file exists to avoid. ---- */
  [/^(planks|\w+_planks|bamboo_mosaic)$/, 'building_blocks', 'every plank and the bamboo mosaic'],
  [/brick|cobblestone|_tiles$|stone_bricks$/, 'building_blocks',
    'everything brick- or cobble-shaped: the player stacked it, so it builds'],
  [/^(smooth_stone|polished_\w+|chiseled_\w+|cut_\w+|\w+_pillar|quartz_block|purpur_block|sandstone|red_sandstone|smooth_sandstone|smooth_red_sandstone|smooth_quartz|sea_lantern)$/,
    'building_blocks', 'the worked stone shapes -- polished, chiselled, cut, pillared'],
  [/^(cut|exposed_cut|weathered_cut|oxidized_cut|chiseled|exposed_chiseled|weathered_chiseled|oxidized_chiseled)_copper$|^copper_(bulb|grate)$/,
    'building_blocks', 'cut and chiselled copper are shapes a player makes'],
  [/^(cracked_\w+|mossy_\w+|gilded_blackstone|polished_basalt|quartz_bricks|resin_bricks)$/,
    'building_blocks', 'the weathered and decorative stone variants'],
  // Packed mud is crafted (mud + wheat), never generated, so it is Building
  // Blocks while plain mud two rules up is Natural. Same material, opposite
  // tabs, and vanilla splits them the same way.
  [/^packed_mud$/, 'building_blocks', 'Packed Mud is a crafted block, not a generated one'],
]

/**
 * The suffix that marks a block generated by `nonCubeSet()`. Same regex as
 * sounds.js's, and for the same reason: a slab must never be classified by
 * the word "slab", it must be classified as whatever its source cube is.
 */
const NON_CUBE_SUFFIX = /_(slab|slab_top|stairs)$|_stairs_(north|south|east|west)_(top|bottom)$/

/** Which tab claims this item key, as `{ tab, why }`, or null if none does. */
export function ruleFor(key) {
  for (const [pattern, tab, why] of RULES) if (pattern.test(key)) return { tab, why }
  const stripped = key.replace(NON_CUBE_SUFFIX, '')
  if (stripped !== key) {
    /*
     * A family prefix is one of two things, exactly as in sounds.js. Usually
     * it names a block the rules already answer (`deepslate_brick`,
     * `smooth_sandstone`). For the eight wood families it is the bare wood
     * (`oak`, `cherry`), which names no block, so it is asked again as
     * `<wood>_planks` -- the cube nonCubeSet() actually built it from.
     */
    const inherited = ruleFor(stripped) ?? ruleFor(`${stripped}_planks`)
    if (inherited) return { tab: inherited.tab, why: `${inherited.why} (from ${stripped})` }
  }
  return null
}

/* ------------------------------------------------------------------ *
 * The entries: every item, which is now one entry per slab/stair FAMILY.
 *
 * THIS REVERSES AN EARLIER DECISION, and the reversal is the owner's:
 *
 *   "why are there different blocks for different orientations? There is a
 *    top variant? Not even sure what that means, direction of a stair should
 *    depend on how you place it like real minecraft. If that is not currently
 *    the case that should definitely be the case"
 *
 * It was already the case. blockMeshes.js's installPlacementOrientation takes
 * the facing from the player's heading and the half from the face clicked --
 * vanilla's rule, asserted in test/17-non-cube.spec.js -- so the ten ids in a
 * family were never something a player had to choose between. This picker was
 * the only place they were visible, because an earlier reading of "yes, one
 * slot for each, give me access to all blocks" took it to mean one slot per
 * registered ID rather than access to the whole palette.
 *
 * The cost of that reading, in his words: he clicked what looked like a
 * prismarine block and got upside-down stairs. Ten entries deep in a scroll
 * of 82 rows, sharing one name and one texture, with the block key in a
 * tooltip doing all the work.
 *
 * So the ten collapse to two -- one Slab, one Stairs -- and that is vanilla's
 * arrangement exactly. The nine variant ids still exist, because a noa block
 * mesh is a thin instance and orientation therefore HAS to be the id; they
 * are simply not items any more, and items.js is where that is decided (see
 * `isOrientationVariant`), so /give and a dropped stack agree with the picker
 * instead of each having their own idea.
 *
 * Entry count: 731 before, 507 now -- 224 fewer, which is 28 families times
 * the eight ids each of them stopped listing.
 *
 * WATER, LAVA AND THE BARRIER are the three registered blocks with no entry
 * of their own and no family to reach them through, and that is items.js's
 * call rather than this file's: none of the three has an ITEM at all. Vanilla
 * has no water or lava item either (it has a bucket, which is a different
 * object with different rules), and a barrier is `invisible`, so there is no
 * icon to draw. See the note above BLOCK_ITEMS.
 * ------------------------------------------------------------------ */
export const PICKER_ITEMS = ITEMS

/**
 * Every picker item no rule claims.
 *
 * The whole point of enumerating Building Blocks instead of defaulting to it:
 * an uncategorised item is a NAME, in a list, in a failing test -- not a
 * mystery block quietly sitting in a tab nobody scrolls to.
 */
export const uncategorisedItems = () =>
  PICKER_ITEMS.filter(i => !ruleFor(i.key)).map(i => i.key)

/** tab id -> the item ids in it, resolved once at module load. */
const BY_TAB = new Map(CATEGORY_TABS.map(t => [t.id, []]))
for (const it of PICKER_ITEMS) {
  const hit = ruleFor(it.key)
  if (hit) BY_TAB.get(hit.tab).push(it.id)
}

/**
 * The item ids in a tab, in the order they are drawn.
 *
 * Registry order, which is blocks.js's id order, which is already grouped by
 * material family (all the copper together, all the wool together). Vanilla
 * has its own hand-authored order inside each tab; reproducing it means
 * transcribing 500 lines of another game's source, and registry order already
 * puts like next to like, which is the readable property that order buys.
 */
export const tabItems = (id) => BY_TAB.get(id) ?? []

/*
 * An empty tab reads as a broken screen, so a tab that lost its last item is
 * a build-time error rather than a blank panel. Throws at module load, the
 * same way blocks.js throws on a duplicate key -- see the note above TABS for
 * the three vanilla tabs this world deliberately does not declare.
 */
for (const t of CATEGORY_TABS) {
  if (!BY_TAB.get(t.id).length) throw new Error(`creative tab "${t.id}" has no items`)
}

/*
 * The Search tab's default listing: every item, concatenated IN TAB ORDER.
 *
 * Not registry order, and that is vanilla, from the 1.19.3 changelog: "The
 * search tab now lists items sequentially grouped by the other tabs. For
 * example, items found in building blocks always appear before items in
 * redstone blocks." An item that appears in two tabs is listed once, at its
 * first occurrence (minecraft.wiki/w/Creative_inventory) -- nothing here is
 * in two tabs today, but the Set makes that stay true if a rule ever puts it
 * in one, instead of showing a duplicate.
 */
const ALL_IN_TAB_ORDER = [...new Set(CATEGORY_TABS.flatMap(t => tabItems(t.id)))]

/**
 * Case-insensitive substring match on the display name -- what vanilla's
 * Search tab does with a plain query. An empty query lists everything.
 *
 * The key is matched too, with spaces turned into underscores, so "oak stairs"
 * and "oak_stairs" both work. Vanilla additionally supports `#tag` queries
 * against the item tag registry; this world has no tag registry, so a `#` is
 * ordinary text here rather than a syntax that silently matches nothing.
 */
export function searchItems(query) {
  const q = query.trim().toLowerCase()
  if (!q) return ALL_IN_TAB_ORDER
  const asKey = q.replace(/\s+/g, '_')
  const match = (id) => {
    const it = ITEM_BY_ID.get(id)
    return it.name.toLowerCase().includes(q) || it.key.includes(asKey)
  }
  return ALL_IN_TAB_ORDER.filter(match)
}

const ITEM_BY_ID = new Map(PICKER_ITEMS.map(i => [i.id, i]))

/* ------------------------------------------------------------------ *
 * What a click on the LIST does.
 *
 * This is the half of the feature people notice, because every rule differs
 * from the survival screen -- the list is an infinite source, not a
 * container, so nothing is conserved and "swap" has no meaning.
 *
 * All of it from minecraft.wiki/w/Creative_inventory, quoted in each case,
 * and it is worth reading before assuming: A PLAIN LEFT-CLICK DOES NOT GIVE
 * A FULL STACK. It gives one, and clicking again adds one more. The full
 * stack is on SHIFT, on middle-click and on the number keys. That surprises
 * people (it surprised me) and it is what the current wiki says and what the
 * current source does -- 1.8 really did hand you 64 on a plain click, and
 * that is the version most of the folklore comes from.
 *
 * Returned rather than applied, so the rules are a pure function the spec can
 * drive without a screen. `null` means "no change".
 * ------------------------------------------------------------------ */
export function creativeListClick(carried, id, { button = 'left', shift = false } = {}) {
  const max = stackMax(id)
  // "Shift-clicking an item grabs a full stack of items." -- and it does so
  // whether or not you are already carrying something, which is why this is
  // the first test rather than a branch inside the ones below.
  if (shift) return { id, count: max }

  // "Left or right-clicking with an item or stack of items while hovering
  // over any item other than the one held gets rid of the held item." The
  // list is a bin as well as a source, which is how you delete in creative
  // without finding the destroy slot.
  if (carried && carried.id !== id) return null

  if (!carried) {
    // "A single item can be grabbed using left-click". A right-click on an
    // empty cursor picks up one too -- the difference only shows on the
    // second click, below.
    return { id, count: 1 }
  }

  // Same item already on the cursor.
  if (button === 'left') {
    // "...increasing with continued left-clicks on that item", up to the cap.
    return carried.count >= max ? carried : { id, count: carried.count + 1 }
  }
  // "Right-clicking an item also picks up one item, but the second click then
  // puts it back down as opposed to picking up more."
  return carried.count <= 1 ? null : { id, count: carried.count - 1 }
}

/**
 * A full stack of this item.
 *
 * What middle-click, shift-click and the number keys all hand you. For a tool
 * or a piece of armor that is ONE item, because `stackMax` is 1 for them --
 * the wiki does not cover the non-stackable case, but "a full stack" and "the
 * maximum stack size" are the same sentence in the source.
 */
export const fullStack = (id) => ({ id, count: stackMax(id) })

/*
 * Every registered block with no entry in the picker, which should be exactly
 * water, lava and the barrier -- the three that items.js gives no item at all.
 *
 * Derived rather than asserted against a count, so the spec keeps meaning the
 * same thing as the palette grows. A new block that quietly fails to become
 * an item shows up here as a name, which is the same bargain
 * `uncategorisedItems()` makes one section up.
 */
export const blocksWithoutEntry = () => {
  const have = new Set(PICKER_ITEMS.map(i => i.id))
  // REACHABLE, not listed. An orientation variant has no entry of its own on
  // purpose and is reached by placing its family's entry, which is what
  // `drops` points at -- the same redirection the loot table uses. Asking for
  // "no entry" instead would report 280 blocks that are working correctly,
  // and a report nobody can read is a report nobody checks.
  const reachable = (b) => have.has(b.id) || (b.drops !== undefined && have.has(b.drops))
  /*
   * ...and the same redirection AGAIN for the blocks whose canonical id is
   * itself entry-less. The sixteen fluid flow levels are variants of water and
   * lava exactly the way a north-facing stair is a variant of a stair, and
   * `drops` says so -- but water has no picker entry to be reached THROUGH, so
   * the clause above cannot rescue them and all sixteen would be reported as
   * uncategorised blocks. They are not uncategorised. They are water.
   *
   * So report the CANONICAL id instead of the variant, and de-duplicate: the
   * answer stays "water, lava and the barrier", which is the true statement,
   * rather than growing by fourteen names that all mean one of those two.
   */
  const canonical = (b) => (b.drops !== undefined ? BLOCK_BY_ID.get(b.drops) ?? b : b)
  return [...new Set(BLOCK_TYPES.filter(b => !reachable(b)).map(b => canonical(b).key))]
}
